# Generated by Django 3.2.22 on 2023-10-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=35, unique=True)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('category_image', models.ImageField(blank=True, upload_to='images/categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
