# Generated by Django 3.2.22 on 2023-10-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('item_id', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, max_length=60)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
