# Generated by Django 3.2.22 on 2023-12-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
